[project]
name = "lab-3"
version = "0.1.0"
description = "A"
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "beeai-framework>=0.1.16",
    "beeai-sdk>=0.0.22",
    "pydantic-settings>=2.7.1",
    "pydantic>=2.10.6",
]

[project.scripts]
server = "src.agent:server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"